### ISSUE TITLE
Number와 String 계산 형변환 시 결과가 모호함

### ISSUE THREAD

**Issue by kiwiyou** [GeubsikLang/GeubsikCpp#1]
[Extended 급식어 스펙 형변환 부분](https://github.com/GeubsikLang/GeubsikCpp/blob/master/doc/ExtendedGeubsikLang.md#%ED%98%95-%EB%B3%80%ED%99%98)에서는,

> - `number`와 `string`: `string`이 숫자일 경우 `number`로 형 변환됩니다.

라고 설명하고 있습니다. 그런데 `number`와 `string`에서 `string`이 숫자가 아닐 경우에는 따로 처리를 명시하지 않습니다. 동작을 정의하지 않았다고 명시하거나 빠진 동작을 보충해야 할 것 같습니다.

**Comment by kmc7468** [comment]
해당 부분의 동작을 정의해 푸시하였습니다. 이슈 닫겠습니다. 감사합니다.

**Comment by kiwiyou** [comment]
@kmc7468 기존에 있던 부분을 지운 이유는 뭔가요?

**Comment by kmc7468** [comment]
두 피연산자의 순서가 바뀌어도 형 변환 규칙은 같습니다. 문서에서 A와 B는 두 피연산자의 순서를 특별히 지정한 것은 아닙니다.
